.TH PAPERWORK 1 "March 2014" "Version 0.1.2"

.SH NAME
paperwork - make papers easily searchable

.SH SYNOPSIS
.B paperwork

.SH DESCRIPTION
.B paperwork
helps to make dead tree grepable.
.br
The basic idea behind Paperwork is "scan & forget" : You should be able to just scan a new document and forget about it until the day you need it again. Let the machine do most of the work.

Paperwork also supports PDF and images import.

.SH OPTIONS
.BI paperwork
has no command line options. However if you start Paperwork from the command line
with a list of files as arguments, Paperwork will start with the listed files in
the "to be tagged" pane.

.SH SEE ALSO
.br
.B Homepage:
https://github.com/jflesch/paperwork
.br

.SH AUTHOR
This manual page was written by Ross Vandegrift <ross@kallisti.us> for the Debian system (but may be used by others).
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
.br
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
